/** \file camera.h
* Header file for the component class.
*/
#ifndef FMODSETTINGS_H
#define FMODSETTINGS_H
#include <fmod.hpp>
//! The component Class
/*!
This class is a simple place holder component
*/

class FmodSettings
{
public:
	FMOD_REVERB_PROPERTIES getReverbPropOFF();
	FMOD_REVERB_PROPERTIES getReverbPropGENERIC();
	FMOD_REVERB_PROPERTIES getReverbPropPADDEDCELL();
	FMOD_REVERB_PROPERTIES getReverbPropROOM();
	FMOD_REVERB_PROPERTIES getReverbPropBATHROOM();
	FMOD_REVERB_PROPERTIES getReverbPropLIVINGROOM();
	FMOD_REVERB_PROPERTIES getReverbPropSTONEROOM();
	FMOD_REVERB_PROPERTIES getReverbPropAUDITORIUM();
	FMOD_REVERB_PROPERTIES getReverbPropCONCERTHALL();
	FMOD_REVERB_PROPERTIES getReverbPropCAVE();
	FMOD_REVERB_PROPERTIES getReverbPropARENA();
	FMOD_REVERB_PROPERTIES getReverbPropHANGAR();
	FMOD_REVERB_PROPERTIES getReverbPropCARPETTEDHALLWAY();
	FMOD_REVERB_PROPERTIES getReverbPropHALLWAY();
	FMOD_REVERB_PROPERTIES getReverbPropSTONECORRIDOR();
	FMOD_REVERB_PROPERTIES getReverbPropALLEY();
	FMOD_REVERB_PROPERTIES getReverbPropFOREST();
	FMOD_REVERB_PROPERTIES getReverbPropCITY();
	FMOD_REVERB_PROPERTIES getReverbPropMOUNTAINS();
	FMOD_REVERB_PROPERTIES getReverbPropQUARRY();
	FMOD_REVERB_PROPERTIES getReverbPropPLAIN();
	FMOD_REVERB_PROPERTIES getReverbPropPARKINGLOT();
	FMOD_REVERB_PROPERTIES getReverbPropSEWERPIPE();
	FMOD_REVERB_PROPERTIES getReverbPropUNDERWATER();

};

#endif FMODSETTINGS_H